#!/usr/bin/env python3

import sys


def format_bytes(size):
    power = 2**10
    n = 0
    power_labels = {0: "", 1: "K", 2: "M", 3: "G", 4: "T"}
    while size > power:
        size /= power
        n += 1
    return f"{size:.2f} {power_labels[n]}B"


if __name__ == "__main__":
    try:
        value = sys.argv.pop(1)
    except IndexError:
        value = sys.stdin.read()

    formatters = {
        "bytes": format_bytes,
    }

    try:
        format = sys.argv[sys.argv.index("-f") + 1]
    except ValueError:
        print("No format specified")
        sys.exit(1)

    if format not in formatters:
        print(
            "Unknown format specified, supported formats are:",
            ", ".join(formatters.keys()),
        )
        sys.exit(1)

    print(formatters[format](int(value)))
